# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CVS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    #- name: Setup x-crypto package
    #  run: git clone https://github.com/LeviMarvin/go-x-crypto.git vendor/golang.org/x/crypto
    
    - name: Build cvscli
      run: go build -o out/cvscli CVS/cmd/cvscli

    - name: Build server
      run: go build -o out/server CVS/cmd/server

    #- name: Test
    #  run: go test -v ./...

    - uses: actions/upload-artifact@v3
      with:
          name: cvs
          path: out/
